version: '3.8'

services:
  postgres:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
    networks:
      - tracking-network

  flask-app:
    build:
      context: ./flask_app
      dockerfile: ../docker/flask/Dockerfile
    env_file:
      - .env
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    volumes:
      - ./flask_app:/app  # Mount local code
      - ./videos:/app/videos
      - ./outputs:/app/outputs
    networks:
      - tracking-network

  object-tracker:
    build:
      context: ./object_tracker
      dockerfile: ../docker/object_tracker/Dockerfile
    env_file:
      - .env
    ports:
      - "5002:5000"
    volumes:
      - ./videos:/app/videos
      - ./object_tracker:/app
      - ./outputs:/app/outputs
    depends_on:
      - flask-app
    networks:
      - tracking-network
    command: ["python3", "-u", "object_tracker_app.py"]

volumes:
  postgres_data:

networks:
  tracking-network:
    driver: bridge